<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-08-24 01:46

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 4.0.3 on 2022-08-24 01:30

from django.db import migrations, models
>>>>>>> main


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('events_app', '0002_alter_event_attendees'),
=======
        ('events_app', '0002_remove_event_attendees_event_attendees_and_more'),
>>>>>>> main
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
<<<<<<< HEAD
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events_app.uservo'),
=======
            field=models.ManyToManyField(blank=True, related_name='users', to='events_app.uservo'),
>>>>>>> main
        ),
    ]
