# Generated by Django 4.0.3 on 2022-08-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_remove_event_attendees_event_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='events_app.uservo'),
        ),
    ]
