# Generated by Django 4.0.3 on 2022-08-31 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events_app", "0004_activity_picture_url"),
        ("events_app", "0004_event_picture_url"),
    ]

    operations = []
