# pull official base image
FROM node:lts-bullseye

# set working directory
WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm install -g
RUN npm install react-scripts@5.0.1 -g 


# start app
CMD ["npm", "start"]
