# pull official base image
FROM node:lts-bullseye

# set working directory
WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm install
RUN npm install react-scripts@5.0.1 -g 
# RUN /bin/bash windows-setup.js
# RUN /bin/bash run.sh

# start app
# CMD /bin/bash -c "npm install; npm install react-scripts@5.0.1 -g; npm start"
CMD ["npm", "start"]
