volumes:
    postgres-data:
        external: true
services:
    react:
        build:
            context: ./frontend-app
            dockerfile: ./Dockerfile.dev
        # image: node:lts-bullseye
        command: /bin/bash run.sh
        # working_dir: /app
        volumes:
            - ./frontend-app:/app
        ports:
            - "3000:3000"
        environment:
            HOST_OS: ${OS}
            NODE_ENV: development
            HOST: "0.0.0.0"
            REACT_APP_GOOGLE_API_KEY: ${GOOGLE_API_KEY}
            REACT_APP_EVENTS: http://localhost:8090
            REACT_APP_USERS: http://localhost:8080
            REACT_APP_MESSENGER: http://localhost:8070
            REACT_APP: http://localhost:3000
    postgres:
        image: postgres:14.2-bullseye
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./relational-data:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_MULTIPLE_DATABASES=events,users,messenger
            - POSTGRES_PASSWORD=password
        ports:
            - 15432:5432
    events:
        build:
            context: ./backend/events
            dockerfile: ./Dockerfile.dev
        ports:
            - "8090:8000"
        volumes:
            - ./backend/events:/app
        environment:
            DATABASE_URL: postgresql://events:password@postgres:5432/events
            WAIT_HOSTS: postgres:5432
            DJWTO_SIGNING_KEY: c0c3ec33213a4ce5f0378c4350846fc35310b3ae3672a8b7f0ffae1a527d38cc
    users:
        build:
            context: ./backend/users
            dockerfile: ./Dockerfile.dev
        ports:
            - "8080:8000"
        volumes:
            - ./backend/users:/app
        environment:
            DATABASE_URL: postgresql://users:password@postgres:5432/users
            WAIT_HOSTS: postgres:5432
            DJWTO_SIGNING_KEY: c0c3ec33213a4ce5f0378c4350846fc35310b3ae3672a8b7f0ffae1a527d38cc
    messenger:
        build:
            context: ./backend/messenger
            dockerfile: ./Dockerfile.dev
        ports:
            - "8070:8000"
        volumes:
            - ./backend/messenger:/app
        environment:
            DATABASE_URL: postgresql://messenger:password@postgres:5432/messenger
            WAIT_HOSTS: postgres:5432
            DJWTO_SIGNING_KEY: c0c3ec33213a4ce5f0378c4350846fc35310b3ae3672a8b7f0ffae1a527d38cc
    users-poller:
        build:
            context: ./backend/users/poll
            dockerfile: ./Dockerfile.dev
        volumes:
            - ./backend/users/poll:/app
            - ./backend/users/users_project:/app/users_project
            - ./backend/users/users_app:/app/users_app
        depends_on:
            - postgres
            - users
        environment:
            DATABASE_URL: postgresql://users:password@postgres:5432/users
            WAIT_HOSTS: postgres:5432
            WAIT_TIMEOUT: 300        
    events-poller:
        build:
            context: ./backend/events/poll
            dockerfile: ./Dockerfile.dev
        volumes:
            - ./backend/events/poll:/app
            - ./backend/events/events_project:/app/events_project
            - ./backend/events/events_app:/app/events_app
        depends_on:
            - postgres
            - events
        environment:
            DATABASE_URL: postgresql://users:password@postgres:5432/events
            WAIT_HOSTS: postgres:5432
            WAIT_TIMEOUT: 300      