volumes:
  postgres-data:
    external: true

services:
  react:
    build:
      context: ./frontend-app
      dockerfile: ./Dockerfile.dev
    # image: node:lts-bullseye
    # command: /bin/bash run.sh
    # working_dir: /app
    volumes:
        - ./frontend-app:/app
    ports:
        - "3000:3000"
    environment:
        HOST_OS: ${OS}
        NODE_ENV: development
        HOST: "0.0.0.0"
  postgres:
    build:
        context: ./relational-data
        dockerfile: ./Dockerfile.dev
    volumes:
        - postgres-data:/var/lib/postgresql/data
    environment:
        - POSTGRES_MULTIPLE_DATABASES=django
        - POSTGRES_PASSWORD=test-databases
    ports:
        - 15432:5432
  django:
    build:
        context: ./backend
        dockerfile: ./Dockerfile.dev
    ports:
        - "8090:8000"
    volumes:
        - ./backend:/app
    environment:
        DATABASE_URL: postgresql://django:password@postgres/django
        WAIT_HOSTS: postgres:5432

