FROM postgres:14.2-bullseye
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install bash -y
COPY create-multiple-databases.sh /docker-entrypoint-initdb.d
RUN chmod a+r /docker-entrypoint-initdb.d/*