# Generated by Django 4.0.3 on 2022-08-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('friend', models.ManyToManyField(to='users_app.user', verbose_name='friend')),
            ],
        ),
    ]
