# Generated by Django 4.0.3 on 2022-08-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityvo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
