# Generated by Django 4.0.3 on 2022-08-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(null=True, to='users_app.user', verbose_name='friend'),
        ),
    ]
