# Generated by Django 4.0.3 on 2022-08-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_user_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(blank=True, to='users_app.user', verbose_name='friend'),
        ),
    ]
