# Generated by Django 4.0.3 on 2022-08-29 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0003_user_friend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="friend",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
