# Generated by Django 4.0.3 on 2022-08-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0002_alter_activityvo_id"),
        ("users_app", "0005_rename_friend_user_friends"),
    ]

    operations = []
