# Generated by Django 4.0.3 on 2022-09-21 23:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0011_remove_user_friend_requests_user_friend_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sent_requests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
